version: '2.6.1'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/books
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/usr/src/config
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/usr/src/config
    depends_on:
      - django
      - redis


  redis:
    image: redis:alpine
    command: redis-server

  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - 5557:5555
    depends_on:
      - redis

volumes:
  postgres_data: