# Generated by Django 4.0.6 on 2022-08-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_categorybooks_book_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
