# Generated by Django 4.0.6 on 2022-08-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
