# Generated by Django 4.0.6 on 2022-08-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_author_link_alter_author_name_alter_book_author'),
    ]

    operations = [
    ]
