# Generated by Django 4.0.6 on 2022-08-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_transfer_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_link',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author'),
        ),
    ]
