# Generated by Django 4.1 on 2022-08-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_review_date_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='without decription', null=True),
        ),
    ]
