# Generated by Django 4.1 on 2022-08-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='', max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='agecontrol',
            field=models.CharField(default='0+', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='copyright',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
