# Generated by Django 4.1 on 2022-08-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_isbn_book_agecontrol_book_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ispopular',
            field=models.BooleanField(default=False),
        ),
    ]
