# Generated by Django 4.1 on 2022-08-15 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0014_book_ispopular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('summ', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('secondname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('numberphone', models.PositiveIntegerField(verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('fulladdress', models.CharField(max_length=255, verbose_name='Область(республика),Город,улица,дом,квартира,индекс:')),
                ('notification', models.BooleanField(default=False, verbose_name='СМС уведомление о статусе заказа')),
                ('status', models.CharField(choices=[('New', 'New'), ('Paid', 'Paid'), ('Accepted', 'Accepted'), ('On the way', 'Ontheway'), ('Delivered', 'Delivered')], default='New', max_length=255)),
                ('Payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.paymentmethod')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.orderbooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
    ]
