# Generated by Django 4.1 on 2022-08-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_paymentmethod_orderbooks_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.AddField(
            model_name='orderbooks',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'New'), ('Оплачено', 'Paid'), ('Принят', 'Accepted'), ('В пути', 'Ontheway'), ('Доставлен', 'Delivered')], default='Новый', max_length=255),
        ),
    ]
