# Generated by Django 4.1 on 2022-08-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.paymentmethod', verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='numberphone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
