# Generated by Django 4.1 on 2022-08-17 03:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_order_payment_alter_order_numberphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbooks',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='BooksInOrder',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.orderbooks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='fulladdress',
            field=models.CharField(max_length=255, verbose_name='Область(республика),город,улица,дом,квартира,индекс:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='numberphone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
