# Generated by Django 4.1 on 2022-08-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_remove_orderbooks_order_order_booksinorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='BooksInOrder',
        ),
    ]
