# Generated by Django 4.1 on 2022-08-17 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_remove_order_booksinorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='BooksInOrder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.orderbooks'),
            preserve_default=False,
        ),
    ]
