# Generated by Django 4.1 on 2022-08-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_order_booksinorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='BooksInOrder',
        ),
        migrations.AddField(
            model_name='orderbooks',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.order'),
        ),
    ]
